# Basic
title: deepindo
subtitle: æˆ‘çš„ç¬”è®°æœ¬
description: èµ°åœ¨å¼€å‘çš„è·¯ä¸Š~~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: deepindo
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: iOS / æœºå™¨å­¦ä¹ 
url: "http://deepindo.io"

# Comment
comment:
    # disqus: deepindo
    duoshuo: deepindo 

# Social
social:
    weibo: bingtian1989 
    github: deepindo
    # twitter: 
    mail: deepindo@sina.com

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
#baidu:
    #id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
#ga:
    #id: UA-84134159-3   
    #host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/deepindo/deepindo.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºæˆ‘, description: about, url: '/about'}      
    

# Pagination
#gems: [jekyll-paginate,jekyll-sitemap]
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"


